# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../qtcreator-ui/SudokuSolver/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 776)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 328, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sudokuInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.sudokuInput.setObjectName("sudokuInput")
        self.horizontalLayout.addWidget(self.sudokuInput)
        self.sudokuLoad = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sudokuLoad.setObjectName("sudokuLoad")
        self.horizontalLayout.addWidget(self.sudokuLoad)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.solveButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.solveButton.setObjectName("solveButton")
        self.horizontalLayout_2.addWidget(self.solveButton)
        self.big_solve = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.big_solve.setObjectName("big_solve")
        self.horizontalLayout_2.addWidget(self.big_solve)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridEditMode = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.gridEditMode.setObjectName("gridEditMode")
        self.verticalLayout.addWidget(self.gridEditMode)
        self.sudokuTableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.sudokuTableWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sudokuTableWidget.sizePolicy().hasHeightForWidth())
        self.sudokuTableWidget.setSizePolicy(sizePolicy)
        self.sudokuTableWidget.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.sudokuTableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sudokuTableWidget.setLineWidth(1)
        self.sudokuTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.sudokuTableWidget.setTabKeyNavigation(False)
        self.sudokuTableWidget.setAlternatingRowColors(False)
        self.sudokuTableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.sudokuTableWidget.setRowCount(9)
        self.sudokuTableWidget.setColumnCount(9)
        self.sudokuTableWidget.setObjectName("sudokuTableWidget")
        self.sudokuTableWidget.horizontalHeader().setVisible(False)
        self.sudokuTableWidget.horizontalHeader().setDefaultSectionSize(30)
        self.sudokuTableWidget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.sudokuTableWidget)
        self.exportGridButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.exportGridButton.setObjectName("exportGridButton")
        self.verticalLayout.addWidget(self.exportGridButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(359, 4, 381, 501))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fileSelectButton = QtWidgets.QToolButton(self.verticalLayoutWidget_2)
        self.fileSelectButton.setObjectName("fileSelectButton")
        self.verticalLayout_2.addWidget(self.fileSelectButton)
        self.sudokuDbList = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sudokuDbList.sizePolicy().hasHeightForWidth())
        self.sudokuDbList.setSizePolicy(sizePolicy)
        self.sudokuDbList.setObjectName("sudokuDbList")
        self.verticalLayout_2.addWidget(self.sudokuDbList)
        self.solutionsTree = QtWidgets.QTreeWidget(self.verticalLayoutWidget_2)
        self.solutionsTree.setObjectName("solutionsTree")
        self.solutionsTree.headerItem().setText(0, "1")
        self.verticalLayout_2.addWidget(self.solutionsTree)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(29, 519, 711, 151))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.out_box = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_3)
        self.out_box.setEnabled(True)
        self.out_box.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.out_box.setFocusPolicy(QtCore.Qt.NoFocus)
        self.out_box.setReadOnly(True)
        self.out_box.setCenterOnScroll(True)
        self.out_box.setObjectName("out_box")
        self.verticalLayout_3.addWidget(self.out_box)
        self.in_box = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.in_box.setObjectName("in_box")
        self.verticalLayout_3.addWidget(self.in_box)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 22))
        self.menubar.setObjectName("menubar")
        self.menuSolveur_de_Sudoku_de_Jean_Ribes = QtWidgets.QMenu(self.menubar)
        self.menuSolveur_de_Sudoku_de_Jean_Ribes.setObjectName("menuSolveur_de_Sudoku_de_Jean_Ribes")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuSolveur_de_Sudoku_de_Jean_Ribes.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Solveur de sudoku de Jean Ribes"))
        self.sudokuLoad.setText(_translate("MainWindow", "Charger ce sudoku"))
        self.solveButton.setText(_translate("MainWindow", "Résolution rapide"))
        self.big_solve.setText(_translate("MainWindow", "Résoudre backtrack"))
        self.gridEditMode.setText(_translate("MainWindow", "Éditer le sudoku"))
        self.exportGridButton.setText(_translate("MainWindow", "Exporter la grille"))
        self.fileSelectButton.setText(_translate("MainWindow", "Séléctionner un fichier de sudokus"))
        self.fileSelectButton.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.menuSolveur_de_Sudoku_de_Jean_Ribes.setTitle(_translate("MainWindow", "Solveur de Sudoku de Jean Ribes"))
