# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../qtcreator-ui/SudokuSolver/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1029, 860)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.debugBox = QtWidgets.QGroupBox(self.centralwidget)
        self.debugBox.setGeometry(QtCore.QRect(50, 550, 681, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.debugBox.sizePolicy().hasHeightForWidth())
        self.debugBox.setSizePolicy(sizePolicy)
        self.debugBox.setMinimumSize(QtCore.QSize(0, 0))
        self.debugBox.setAutoFillBackground(True)
        self.debugBox.setObjectName("debugBox")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.debugBox)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 35, 631, 161))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.debugLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.debugLayout.setContentsMargins(10, 10, 10, 10)
        self.debugLayout.setObjectName("debugLayout")
        self.out_box = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_3)
        self.out_box.setEnabled(True)
        self.out_box.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.out_box.setFocusPolicy(QtCore.Qt.NoFocus)
        self.out_box.setReadOnly(True)
        self.out_box.setCenterOnScroll(True)
        self.out_box.setObjectName("out_box")
        self.debugLayout.addWidget(self.out_box)
        self.in_box = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.in_box.setObjectName("in_box")
        self.debugLayout.addWidget(self.in_box)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(20, 10, 991, 531))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.selectBox = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectBox.sizePolicy().hasHeightForWidth())
        self.selectBox.setSizePolicy(sizePolicy)
        self.selectBox.setObjectName("selectBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.selectBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 40, 461, 471))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.selectLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.selectLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.selectLayout.setContentsMargins(0, 0, 0, 3)
        self.selectLayout.setObjectName("selectLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sudokuInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.sudokuInput.setObjectName("sudokuInput")
        self.horizontalLayout.addWidget(self.sudokuInput)
        self.sudokuLoad = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.sudokuLoad.setObjectName("sudokuLoad")
        self.horizontalLayout.addWidget(self.sudokuLoad)
        self.selectLayout.addLayout(self.horizontalLayout)
        self.fileSelectButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.fileSelectButton.setObjectName("fileSelectButton")
        self.selectLayout.addWidget(self.fileSelectButton)
        self.sudokuDbList = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sudokuDbList.sizePolicy().hasHeightForWidth())
        self.sudokuDbList.setSizePolicy(sizePolicy)
        self.sudokuDbList.setObjectName("sudokuDbList")
        self.selectLayout.addWidget(self.sudokuDbList)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout.setObjectName("formLayout")
        self.previousButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.previousButton.setObjectName("previousButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.previousButton)
        self.nextButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.nextButton.setObjectName("nextButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nextButton)
        self.selectLayout.addLayout(self.formLayout)
        self.sudokuContainer = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sudokuContainer.sizePolicy().hasHeightForWidth())
        self.sudokuContainer.setSizePolicy(sizePolicy)
        self.sudokuContainer.setObjectName("sudokuContainer")
        self.layoutWidget = QtWidgets.QWidget(self.sudokuContainer)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 451, 481))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.solveButton = QtWidgets.QPushButton(self.layoutWidget)
        self.solveButton.setObjectName("solveButton")
        self.horizontalLayout_2.addWidget(self.solveButton)
        self.big_solve = QtWidgets.QPushButton(self.layoutWidget)
        self.big_solve.setObjectName("big_solve")
        self.horizontalLayout_2.addWidget(self.big_solve)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridEditMode = QtWidgets.QCheckBox(self.layoutWidget)
        self.gridEditMode.setObjectName("gridEditMode")
        self.verticalLayout.addWidget(self.gridEditMode)
        self.sudokuTableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        self.sudokuTableWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sudokuTableWidget.sizePolicy().hasHeightForWidth())
        self.sudokuTableWidget.setSizePolicy(sizePolicy)
        self.sudokuTableWidget.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.sudokuTableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sudokuTableWidget.setLineWidth(1)
        self.sudokuTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.sudokuTableWidget.setTabKeyNavigation(False)
        self.sudokuTableWidget.setAlternatingRowColors(False)
        self.sudokuTableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.sudokuTableWidget.setRowCount(9)
        self.sudokuTableWidget.setColumnCount(9)
        self.sudokuTableWidget.setObjectName("sudokuTableWidget")
        self.sudokuTableWidget.horizontalHeader().setVisible(False)
        self.sudokuTableWidget.horizontalHeader().setDefaultSectionSize(30)
        self.sudokuTableWidget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.sudokuTableWidget)
        self.exportGridButton = QtWidgets.QPushButton(self.layoutWidget)
        self.exportGridButton.setObjectName("exportGridButton")
        self.verticalLayout.addWidget(self.exportGridButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Solveur de sudoku de Jean Ribes"))
        self.debugBox.setTitle(_translate("MainWindow", "Interpréteur de debug"))
        self.selectBox.setTitle(_translate("MainWindow", "Sélection du Sudoku"))
        self.sudokuLoad.setText(_translate("MainWindow", "Charger ce sudoku"))
        self.fileSelectButton.setText(_translate("MainWindow", "Séléctionner un fichier de sudokus"))
        self.fileSelectButton.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.previousButton.setText(_translate("MainWindow", "⟨ Précédent"))
        self.nextButton.setText(_translate("MainWindow", "Suivant ⟩"))
        self.sudokuContainer.setTitle(_translate("MainWindow", "Sudoku"))
        self.solveButton.setText(_translate("MainWindow", "Résolution rapide"))
        self.big_solve.setText(_translate("MainWindow", "Résoudre backtrack"))
        self.gridEditMode.setText(_translate("MainWindow", "Éditer le sudoku"))
        self.exportGridButton.setText(_translate("MainWindow", "Exporter la grille"))
